openapi: 3.0.1
info:
  title: IVP
  description: ''
  version: 1.0.0
tags:
  - name: 客户
paths:
  /company/all:
    get:
      summary: 获取全部记录
      deprecated: false
      description: ''
      tags:
        - 客户
        - 客户
      parameters:
        - name: Authorization
          in: header
          description: ''
          required: false
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDdHhDb3Jwb3JhdGlvbklkIjpudWxsLCJjdHhVc2VySWQiOjExLCJleHAiOjE3MDAyMDA3MjIsIm9yaWdfaWF0IjoxNzAwMTg2MzIyfQ.x4VlmkMMtukLknz6e8ftSFM0x_J1ZUc4K0gBYVXw2tU
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nxos-admin.api.v1.company.AllRes'
          headers: {}
          x-apifox-name: 成功
      security:
        - bearer: []
      x-apifox-folder: 客户
      x-apifox-status: released
      x-run-in-apifox: https://app.apifox.com/web/project/3441005/apis/api-138073454-run
components:
  schemas:
    nxos-admin.api.v1.company.AllRes:
      items:
        $ref: '#/components/schemas/nxos-admin.api.v1.company.ListCompany'
      properties: {}
      type: array
      x-apifox-folder: Schemas
    nxos-admin.api.v1.company.ListCompany:
      properties:
        id:
          format: int
          properties: {}
          type: integer
        name:
          format: string
          properties: {}
          type: string
        code:
          format: string
          properties: {}
          type: string
        createAt:
          format: '*gtime.Time'
          properties: {}
          type: string
        updateAt:
          format: '*gtime.Time'
          properties: {}
          type: string
        status:
          format: int
          properties: {}
          type: integer
        deleteAt:
          format: '*gtime.Time'
          properties: {}
          type: string
        remark:
          format: string
          properties: {}
          type: string
        threshold:
          format: int
          properties: {}
          type: integer
        minCurrent:
          format: int
          properties: {}
          type: integer
        balance:
          format: float64
          properties: {}
          type: number
        alwaysOn:
          format: int
          properties: {}
          type: integer
        closeThreshold:
          format: int
          properties: {}
          type: integer
        isSystem:
          format: int
          properties: {}
          type: integer
        credit:
          format: float64
          properties: {}
          type: number
        corporationId:
          format: int
          properties: {}
          type: integer
        billType:
          format: int
          properties: {}
          type: integer
        billingCycle:
          format: string
          properties: {}
          type: string
        balanceRiskControl:
          format: int
          properties: {}
          type: integer
        creatorId:
          format: int
          properties: {}
          type: integer
        customerId:
          format: int
          properties: {}
          type: integer
        closeAlarmThreshold:
          format: int
          properties: {}
          type: integer
        creatorName:
          format: string
          properties: {}
          type: string
      type: object
      x-apifox-orders:
        - id
        - name
        - code
        - createAt
        - updateAt
        - status
        - deleteAt
        - remark
        - threshold
        - minCurrent
        - balance
        - alwaysOn
        - closeThreshold
        - isSystem
        - credit
        - corporationId
        - billType
        - billingCycle
        - balanceRiskControl
        - creatorId
        - customerId
        - closeAlarmThreshold
        - creatorName
      x-apifox-ignore-properties: []
      x-apifox-folder: Schemas
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers:
  - url: https://ivp-test.nxcloud.com/nxos-admin
    description: '对外测试环境 '
security:
  - bearer: []
