openapi: 3.0.1
info:
  title: nxai-bot
  description: ''
  version: 1.0.0
tags:
  - name: mgr
  - name: mgr/对外api外呼任务管理
  - name: Call List
paths:
  /openapi/aiagent/call/list:
    post:
      summary: 对外api 通话记录
      deprecated: false
      description: ''
      tags:
        - mgr/对外api外呼任务管理
        - Call List
      parameters:
        - name: accessKey
          in: header
          description: ''
          required: true
          example: 'AK-1961228596103496364-4784'
          schema:
            type: string
        - name: accessSecret
          in: header
          description: '此参数仅文档中测试使用，实际使用时请在签名中使用'
          required: true
          example: 'a5824077337e44f9b629d9c8276e643d'
          schema:
            type: string
        - name: bizType
          in: header
          description: ''
          required: true
          example: '100'
          schema:
            type: string
        - name: action
          in: header
          description: ''
          required: true
          example: 'nxai'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: string
                startTs:
                  type: string
                endTs:
                  type: integer
                userIntent:
                  type: string
                pageNumber:
                  type: integer
                pageSize:
                  type: integer
              required:
                - taskId
                - startTs
                - endTs
                - userIntent
                - pageNumber
                - pageSize
            example:
              taskId: 8bdf2a84-fc89-483e-ba1e-35a54285c7d0
              startTs: '1736215928'
              endTs: 1746583929
              userIntent: ''
              pageNumber: 1
              pageSize: 10
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers:
  - url: https://test-api-westus.nxlink.ai
    description: '对外测试环境 '
security: []
